project:
  type: website

website:
  title: "Occupación tigrinus"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/dlizcano/tigrinus_occu
        aria-label: GitHub

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

